Repository googleapis/nodejs-secret-manager, pull requests merged in 2020-11, with the labels that each got.

#183 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full

#184 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/secret_manager_service_client.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: secretmanager, cla: yes

#187 fix: do not modify options object, use defaultScopes
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes

#191 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/secret_manager_service_client.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
Labels: api: secretmanager, cla: yes, context: none

#193 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: secretmanager, automerge, cla: yes, context: full
