Repository googleapis/nodejs-secret-manager, pull requests merged in 2020-09, with the labels that each got.

#161 build: delete Blunderbuss
  .github/blunderbuss.yml
Labels: api: secretmanager, cla: yes

#162 docs: clean up redundant comments
  protos/google/cloud/secretmanager/v1/service.proto
  protos/google/cloud/secrets/v1beta1/service.proto
  synth.metadata
Labels: cla: yes, context: full

#165 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#164 feat: update secretmanager.googleapis.com v1 protos
  protos/google/cloud/secretmanager/v1/resources.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: secretmanager, cla: yes, context: full
