Repository googleapis/nodejs-secret-manager, pull requests merged in 2020-07, with the labels that each got.

#135 build: use bazel build
  src/v1/secret_manager_service_client.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
  synth.py
  test/gapic_secret_manager_service_v1.ts
  test/gapic_secret_manager_service_v1beta1.ts
Labels: automerge, cla: yes

#136 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#139 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#141 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#142 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#143 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#144 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#145 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 build: update protos
  .kokoro/release/docs-devsite.cfg
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: partial
