Repository googleapis/nodejs-secret-manager, pull requests merged in 2020-06, with the labels that each got.

#122 docs: update quickstart on readme
  README.md
  synth.metadata
Labels: cla: yes, context: none

#123 build: upgrade library to GA
  .repo-metadata.json
  README.md
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/secret_manager_service_client.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
  tsconfig.json
Labels: cla: yes

#125 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#128 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v1/secret_manager_service_client.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#130 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#134 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
