Repository googleapis/nodejs-secret-manager, pull requests merged in 2020-05, with the labels that each got.

#111 feat: add Blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#114 chore: update uuid
  samples/package.json
  samples/test/secretmanager.test.js
Labels: automerge, cla: yes

#115 fix: regen protos and tests, formatting
  synth.metadata
  test/gapic_secret_manager_service_v1.ts
  test/gapic_secret_manager_service_v1beta1.ts
Labels: automerge, cla: yes

#116 fix: synth.py clean up for multiple version
  .github/workflows/ci.yaml
  protos/google/cloud/secrets/v1beta1/resources.proto
  protos/google/cloud/secrets/v1beta1/service.proto
  protos/protos.json
  src/index.ts
  src/v1beta1/secret_manager_service_client.ts
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#121 docs: update documentation
  protos/google/cloud/secretmanager/v1/resources.proto
  protos/google/cloud/secretmanager/v1/service.proto
  synth.metadata
Labels: cla: yes, context: full

#117 fix(samples): correct usage of toString()
  README.md
  samples/accessSecretVersion.js
Labels: cla: yes
