Repository googleapis/nodejs-secret-manager, pull requests merged in 2021-03, with the labels that each got.

#207 feat: added topic field to Secret
  protos/google/cloud/secretmanager/v1/resources.proto
  protos/google/cloud/secretmanager/v1/service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/secret_manager_service_client.ts
  synth.metadata
  test/gapic_secret_manager_service_v1.ts
Labels: api: secretmanager, cla: yes, context: full

#211 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: secretmanager, automerge, cla: yes, context: full

#213 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: secretmanager, cla: yes
